spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/demo-project
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

logging.level:
  org.hibernate.SQL: debug
  root: info
#  org.hibernate.type: trace

